name: glucolearn
description: "A comprehensive diabetes education app for interactive learning and progress tracking."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  
  # UI & Icons
  cupertino_icons: ^1.0.8
  
  # State Management
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3
  
  # Navigation
  go_router: ^12.1.3
  
  # Local Storage & Database
  sqflite: ^2.3.0
  path: ^1.8.3
  path_provider: ^2.1.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.2.2
  
  # Media & Video
  video_player: ^2.8.1
  chewie: ^1.7.4
  cached_network_image: ^3.3.0
  
  # Forms & Validation
  flutter_form_builder: ^9.1.1
  form_builder_validators: ^11.1.2
  
  # Charts & Analytics
  fl_chart: ^0.65.0
  
  # Animations
  lottie: ^2.7.0
  
  # Security
  crypto: ^3.0.3
  
  # Firebase
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.3
  firebase_analytics: ^11.3.3
  
  # Utilities
  uuid: ^4.2.2
  file_picker: ^8.1.4
  image_picker: ^1.0.4
  intl: ^0.19.0
  permission_handler: ^11.1.0
  
  # Local Authentication
  local_auth: ^2.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  
  # Code Generation
  build_runner: ^2.4.7
  riverpod_generator: ^2.3.9
  hive_generator: ^2.0.1
  json_serializable: ^6.7.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/videos/
    - assets/animations/
    - assets/documents/
    
  # fonts:
  #   - family: SFProDisplay
  #     fonts:
  #       - asset: assets/fonts/SFProDisplay-Regular.ttf
  #       - asset: assets/fonts/SFProDisplay-Medium.ttf
  #         weight: 500
  #       - asset: assets/fonts/SFProDisplay-Semibold.ttf
  #         weight: 600
  #       - asset: assets/fonts/SFProDisplay-Bold.ttf
  #         weight: 700
